### ISSUE TITLE
Random error in console

### ISSUE THREAD

**Issue by myfbone** [Esophose/PlayerParticles#20]
I have done nothing, but this error appeared in console.
pp version 6.4
paper version124 build (1.14.3)

```
[01:30:05 ERROR]: Could not pass event EntityShootBowEvent to PlayerParticles v6.4
java.lang.ClassCastException: class org.bukkit.craftbukkit.v1_14_R1.entity.CraftSpectralArrow cannot be cast to class org.bukkit.entity.Arrow (org.bukkit.craftbukkit.v1_14_R1.entity.CraftSpectralArrow and org.bukkit.entity.Arrow are in unnamed module of loader 'app')
        at com.esophose.playerparticles.styles.ParticleStyleArrows.onArrowFired(ParticleStyleArrows.java:86) ~[?:?]
        at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor235.execute(Unknown Source) ~[?:?]
        at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:69) ~[patched_1.14.3.jar:git-Paper-124]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[patched_1.14.3.jar:git-Paper-124]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[patched_1.14.3.jar:git-Paper-124]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:536) ~[patched_1.14.3.jar:git-Paper-124]
        at org.bukkit.craftbukkit.v1_14_R1.event.CraftEventFactory.callEntityShootBowEvent(CraftEventFactory.java:485) ~[patched_1.14.3.jar:git-Paper-124]
        at net.minecraft.server.v1_14_R1.ItemBow.a(ItemBow.java:65) ~[patched_1.14.3.jar:git-Paper-124]
        at net.minecraft.server.v1_14_R1.ItemStack.a(ItemStack.java:560) ~[patched_1.14.3.jar:git-Paper-124]
        at net.minecraft.server.v1_14_R1.EntityLiving.clearActiveItem(EntityLiving.java:2952) ~[patched_1.14.3.jar:git-Paper-124]
        at net.minecraft.server.v1_14_R1.PlayerConnection.a(PlayerConnection.java:1289) ~[patched_1.14.3.jar:git-Paper-124]
        at net.minecraft.server.v1_14_R1.PacketPlayInBlockDig.a(SourceFile:40) ~[patched_1.14.3.jar:git-Paper-124]
        at net.minecraft.server.v1_14_R1.PacketPlayInBlockDig.a(SourceFile:10) ~[patched_1.14.3.jar:git-Paper-124]
        at net.minecraft.server.v1_14_R1.PlayerConnectionUtils.lambda$ensureMainThread$0(PlayerConnectionUtils.java:18) ~[patched_1.14.3.jar:git-Paper-124]
        at net.minecraft.server.v1_14_R1.TickTask.run(SourceFile:18) ~[patched_1.14.3.jar:git-Paper-124]
        at net.minecraft.server.v1_14_R1.IAsyncTaskHandler.executeTask(IAsyncTaskHandler.java:127) ~[patched_1.14.3.jar:git-Paper-124]
        at net.minecraft.server.v1_14_R1.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23) ~[patched_1.14.3.jar:git-Paper-124]
        at net.minecraft.server.v1_14_R1.IAsyncTaskHandler.executeNext(IAsyncTaskHandler.java:105) ~[patched_1.14.3.jar:git-Paper-124]
        at net.minecraft.server.v1_14_R1.MinecraftServer.aW(MinecraftServer.java:1002) ~[patched_1.14.3.jar:git-Paper-124]
        at net.minecraft.server.v1_14_R1.MinecraftServer.executeNext(MinecraftServer.java:995) ~[patched_1.14.3.jar:git-Paper-124]
        at net.minecraft.server.v1_14_R1.IAsyncTaskHandler.awaitTasks(IAsyncTaskHandler.java:115) ~[patched_1.14.3.jar:git-Paper-124]
        at net.minecraft.server.v1_14_R1.MinecraftServer.sleepForTick(MinecraftServer.java:979) ~[patched_1.14.3.jar:git-Paper-124]
        at net.minecraft.server.v1_14_R1.MinecraftServer.run(MinecraftServer.java:912) ~[patched_1.14.3.jar:git-Paper-124]
        at java.lang.Thread.run(Thread.java:834) [?:?]
```

**Comment by Esophose** [comment]
Fixed as of latest release
