### ISSUE TITLE
Console commands great!  One found issue -- creating dragon_breath celebration

### ISSUE THREAD

**Issue by gmalone** [Esophose/PlayerParticles#29]
All effects and styles I've tried so far from console work fine _except_ for when using _dragon_breath celebration_.  Doing so generates the following in an endless stream in console, forcing server restart:   --FYI--
`
[05:59:47 WARN]: [PlayerParticles] Task #23490 for PlayerParticles v7.0 generated an exception
java.lang.NullPointerException: null
        at dev.esophose.playerparticles.manager.ParticleManager.displayParticles(ParticleManager.java:187) ~[?:?]
        at dev.esophose.playerparticles.styles.ParticleStyleCelebration$1.run(ParticleStyleCelebration.java:126) ~[?:?]
        at org.bukkit.craftbukkit.v1_14_R1.scheduler.CraftTask.run(CraftTask.java:84) ~[patched_1.14.4.jar:git-Paper-243]
        at org.bukkit.craftbukkit.v1_14_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:452) ~[patched_1.14.4.jar:git-Paper-243]
        at net.minecraft.server.v1_14_R1.MinecraftServer.b(MinecraftServer.java:1171) ~[patched_1.14.4.jar:git-Paper-243]
        at net.minecraft.server.v1_14_R1.DedicatedServer.b(DedicatedServer.java:417) ~[patched_1.14.4.jar:git-Paper-243]
        at net.minecraft.server.v1_14_R1.MinecraftServer.a(MinecraftServer.java:1098) ~[patched_1.14.4.jar:git-Paper-243]
        at net.minecraft.server.v1_14_R1.MinecraftServer.run(MinecraftServer.java:925) ~[patched_1.14.4.jar:git-Paper-243]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_221]
[05:59:47 WARN]: [PlayerParticles] Task #23524 for PlayerParticles v7.0 generated an exception
java.lang.NullPointerException: null
        at dev.esophose.playerparticles.manager.ParticleManager.displayParticles(ParticleManager.java:187) ~[?:?]
        at dev.esophose.playerparticles.styles.ParticleStyleCelebration$1.run(ParticleStyleCelebration.java:126) ~[?:?]
        at org.bukkit.craftbukkit.v1_14_R1.scheduler.CraftTask.run(CraftTask.java:84) ~[patched_1.14.4.jar:git-Paper-243]
        at org.bukkit.craftbukkit.v1_14_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:452) ~[patched_1.14.4.jar:git-Paper-243]
        at net.minecraft.server.v1_14_R1.MinecraftServer.b(MinecraftServer.java:1171) ~[patched_1.14.4.jar:git-Paper-243]
        at net.minecraft.server.v1_14_R1.DedicatedServer.b(DedicatedServer.java:417) ~[patched_1.14.4.jar:git-Paper-243]
        at net.minecraft.server.v1_14_R1.MinecraftServer.a(MinecraftServer.java:1098) ~[patched_1.14.4.jar:git-Paper-243]
        at net.minecraft.server.v1_14_R1.MinecraftServer.run(MinecraftServer.java:925) ~[patched_1.14.4.jar:git-Paper-243]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_221]
`
Upon restart it is apparent that no particles instance was generated.

**Comment by Esophose** [comment]
Issue has already been fixed in commit 1c834c7bb646f29b9b6c71232b508f508ca3a667
Will be posted on Spigot in about 12 hours as v7.1.

Problem is with the celebration style being used as a fixed effect when the player (or console) that owns it is offline.

**Comment by Esophose** [comment]
Here's the jar that will be uploaded in case you want the fix early
[playerparticles-7.1.zip](https://github.com/Esophose/PlayerParticles/files/4198555/playerparticles-7.1.zip)

**Comment by gmalone** [comment]
Thanks.  Got the jar.  Appreciate it.
