### ISSUE TITLE
SQLite Constraint error

### ISSUE THREAD

**Issue by gmalone** [Esophose/PlayerParticles#30]
It doesn't _seem_ to cause any problems function-wise, but I'm seeing this in the console from time to time.  Occurs when invoking _multiple_ **/pp fixed** commands from console.  Just FYI.

`
[11:30:23 ERROR]: [PlayerParticles] An error occurred executing an SQLite query: [SQLITE_CONSTRAINT]  Abort due to constraint violation (UNIQUE constraint failed: playerparticles_fixed.owner_uuid, playerparticles_fixed.id)
[11:30:23 WARN]: org.sqlite.SQLiteException: [SQLITE_CONSTRAINT]  Abort due to constraint violation (UNIQUE constraint failed: playerparticles_fixed.owner_uuid, playerparticles_fixed.id)
[11:30:23 WARN]:        at org.sqlite.core.DB.newSQLException(DB.java:941)
[11:30:23 WARN]:        at org.sqlite.core.DB.newSQLException(DB.java:953)
[11:30:23 WARN]:        at org.sqlite.core.DB.execute(DB.java:854)
[11:30:23 WARN]:        at org.sqlite.core.DB.executeUpdate(DB.java:895)
[11:30:23 WARN]:        at org.sqlite.jdbc3.JDBC3PreparedStatement.executeUpdate(JDBC3PreparedStatement.java:102)
[11:30:23 WARN]:        at dev.esophose.playerparticles.manager.DataManager.lambda$saveFixedEffect$13(DataManager.java:441)
[11:30:23 WARN]:        at dev.esophose.playerparticles.database.SQLiteConnector.connect(SQLiteConnector.java:50)
[11:30:23 WARN]:        at dev.esophose.playerparticles.manager.DataManager.lambda$saveFixedEffect$14(DataManager.java:413)
[11:30:23 WARN]:        at org.bukkit.craftbukkit.v1_15_R1.scheduler.CraftTask.run(CraftTask.java:84)
[11:30:23 WARN]:        at org.bukkit.craftbukkit.v1_15_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:54)
[11:30:23 WARN]:        at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22)
[11:30:23 WARN]:        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
[11:30:23 WARN]:        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
[11:30:23 WARN]:        at java.lang.Thread.run(Thread.java:748)
`

**Comment by Esophose** [comment]
Will look into before v7.1 release

**Comment by Esophose** [comment]
Unable to reproduce. I created 40 fixed effects, removed them randomly, added them back, reset them all, and added them again. The only thing I think could have caused that would be a desync between the database and plugin cache, but that's extremely unlikely and I'm not sure exactly what happened. 

Are you still running into this?

**Comment by gmalone** [comment]
I'll monitor the server tomorrow for this, and let you know if it is recurring, and perhaps some more details.  Thanks.

**Comment by Esophose** [comment]
Closing as no response, going to assume everything is working fine

**Comment by gmalone** [comment]
I apologize for not closing out this issue.  Maybe I did at SpigotMC.  I have not seen the problem any more so whatever was behind it has been resolved.  Thanks a bunch.  And, btw, I love the console functions you've added.  Makes using the particles fx much easier and in many more cases.

**Comment by Esophose** [comment]
All good. Glad you like it :)
