### ISSUE TITLE
World Guard error spam

### ISSUE THREAD

**Issue by MaxWainer** [Esophose/PlayerParticles#48]
Hello! Today I faced with error, PP start spam this error:
```
[22:12:24 WARN]: [PlayerParticles] Task #370 for PlayerParticles v7.15 generated an exception
java.lang.IncompatibleClassChangeError: Found class com.sk89q.worldguard.protection.ApplicableRegionSet, but interface was expected
        at dev.esophose.playerparticles.libs.worldguardwrapper.implementation.legacy.WorldGuardImplementation.getRegions(WorldGuardImplementation.java:114) ~[PlayerParticles_v7.15.jar:?]
        at dev.esophose.playerparticles.libs.worldguardwrapper.WorldGuardWrapper.getRegions(WorldGuardWrapper.java:25) ~[PlayerParticles_v7.15.jar:?]
        at dev.esophose.playerparticles.hook.WorldGuardHook.isInAllowedRegion(WorldGuardHook.java:40) ~[PlayerParticles_v7.15.jar:?]
        at dev.esophose.playerparticles.manager.ParticleManager.updateWorlGuardStatuses(ParticleManager.java:194) ~[PlayerParticles_v7.15.jar:?]
        at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftTask.run(CraftTask.java:59) ~[MG.jar:git-PaperSpigot-"4c7641d"]
        at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:352) [MG.jar:git-PaperSpigot-"4c7641d"]
        at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:783) [MG.jar:git-PaperSpigot-"4c7641d"]
        at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:378) [MG.jar:git-PaperSpigot-"4c7641d"]
        at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:713) [MG.jar:git-PaperSpigot-"4c7641d"]
        at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:616) [MG.jar:git-PaperSpigot-"4c7641d"]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_252]
```

**Comment by Esophose** [comment]
Please make sure you are running the latest versions of WorldGuard and WorldEdit that support 1.8.8.
I went ahead and updated the WorldGuardWrapper library that I'm using in the following jar just in case it being outdated was also the issue: https://ci.codemc.io/job/Esophose/job/PlayerParticles/40/

**Comment by MaxWainer** [comment]
Thank you! Now all work!
