### ISSUE TITLE
Incompatibility with latest WorldGuard - CommandException: WorldEdit does not appear to be enabled

### ISSUE THREAD

**Issue by mibby** [Esophose/PlayerParticles#67]
Paper dev 449 (Spigot 1.16.5)
PlayerParticles v7.17 dev 49
FastAsyncWorldEdit dev 585
WorldGuard dev 2098

@Esophose Did compatibility with WorldGuard break? :( 

Breaking commit from what I can tell. https://github.com/EngineHub/WorldGuard/commit/04d5a3b437aee270e342dc50749f536e0e14ccaf
```
[11:56:24] [Server thread/INFO]: [PlayerParticles] Loading PlayerParticles v7.17
[11:56:24] [Server thread/ERROR]: [org.bukkit.craftbukkit.v1_16_R3.CraftServer] com.sk89q.minecraft.util.commands.CommandException: WorldEdit does not appear to be enabled. initializing PlayerParticles v7.17 (Is it up to date?)
java.lang.RuntimeException: com.sk89q.minecraft.util.commands.CommandException: WorldEdit does not appear to be enabled.
	at dev.esophose.playerparticles.libs.worldguardwrapper.implementation.v7.WorldGuardImplementation.<init>(WorldGuardImplementation.java:68) ~[?:?]
	at dev.esophose.playerparticles.libs.worldguardwrapper.WorldGuardWrapper.<init>(WorldGuardWrapper.java:58) ~[?:?]
	at dev.esophose.playerparticles.libs.worldguardwrapper.WorldGuardWrapper.getInstance(WorldGuardWrapper.java:20) ~[?:?]
	at dev.esophose.playerparticles.hook.WorldGuardHook.initialize(WorldGuardHook.java:28) ~[?:?]
	at dev.esophose.playerparticles.PlayerParticles.onLoad(PlayerParticles.java:97) ~[?:?]
	at org.bukkit.craftbukkit.v1_16_R3.CraftServer.loadPlugins(CraftServer.java:394) ~[patched_1.16.5.jar:git-Tuinity-"2830324"]
	at net.minecraft.server.v1_16_R3.DedicatedServer.init(DedicatedServer.java:207) ~[patched_1.16.5.jar:git-Tuinity-"2830324"]
	at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:937) ~[patched_1.16.5.jar:git-Tuinity-"2830324"]
	at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:174) ~[patched_1.16.5.jar:git-Tuinity-"2830324"]
	at java.lang.Thread.run(Thread.java:832) [?:?]
Caused by: com.sk89q.minecraft.util.commands.CommandException: WorldEdit does not appear to be enabled.
	at com.sk89q.worldguard.bukkit.WorldGuardPlugin.getWorldEdit(WorldGuardPlugin.java:389) ~[?:?]
	at dev.esophose.playerparticles.libs.worldguardwrapper.implementation.v7.WorldGuardImplementation.<init>(WorldGuardImplementation.java:66) ~[?:?]
	... 9 more
```

Downgrading to WorldGuard dev 2088, no error at start-up from PlayerParticles. WorldEdit & WorldGuard initialize fine in both cases, just the later WG dev build causes PP to error.

**Comment by Esophose** [comment]
It broke due to WorldGusrdWrapper doing something wrong and WorldEdit put in an error for it finally. I have it fixed in a dev build you can download: https://ci.codemc.io/job/Esophose/job/PlayerParticles/49/

**Comment by mibby** [comment]
Dev 49 is what I was using when the error occurred.

**Comment by Esophose** [comment]
Sorry, I was half asleep when I replied to you and didn't read that you were already using the latest dev version. Turns out that version didn't actually have the fix in it, try this one: https://ci.codemc.io/job/Esophose/job/PlayerParticles/50/

**Comment by mibby** [comment]
Dev 50 seems to work with the latest WorldGuard dev. Thanks!
